#!/bin/sh
# Generated by scripts/plan_map_chunks.py. Run from the repository root.
# Plan brooklyn_1m_250: 36 plates at 1:10794.
# Every plate shares one print-frame rotation, terrain datum and relief
# factor; changing any of them for a single plate will break the seams.
set -eu

# F1: 223.75 x 93.125 mm, 2.05 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F1.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F1.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_F1 --output output/models/brooklyn_1m_250_F1.3mf

# D1: 221 x 201.125 mm, 3.06 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D1.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D1.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_D1 --output output/models/brooklyn_1m_250_D1.3mf

# G1: 85.375 x 219 mm, 0.54 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G1.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G1.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_G1 --output output/models/brooklyn_1m_250_G1.3mf

# C1: 236 x 235.125 mm, 5.01 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C1.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C1.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_C1 --output output/models/brooklyn_1m_250_C1.3mf

# B2: 51 x 205.875 mm, 0.59 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B2 --output output/models/brooklyn_1m_250_B2.3mf

# A2: 242 x 234.875 mm, 4.66 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_A2 --output output/models/brooklyn_1m_250_A2.3mf

# F2: 250 x 205 mm, 4.42 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_F2 --output output/models/brooklyn_1m_250_F2.3mf

# E2: 95.25 x 245 mm, 1.91 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_E2 --output output/models/brooklyn_1m_250_E2.3mf

# G2: 95.125 x 131 mm, 0.92 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_G2 --output output/models/brooklyn_1m_250_G2.3mf

# C2: 208.625 x 163 mm, 3.14 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_C2 --output output/models/brooklyn_1m_250_C2.3mf

# A2.2: 230 x 197.5 mm, 3.01 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A2.2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A2.2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_A2.2 --output output/models/brooklyn_1m_250_A2.2.3mf

# B3: 114.625 x 71 mm, 0.72 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B3.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B3.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B3 --output output/models/brooklyn_1m_250_B3.3mf

# D3: 239 x 232 mm, 3.37 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D3.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D3.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_D3 --output output/models/brooklyn_1m_250_D3.3mf

# F3: 189 x 151 mm, 2.69 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F3.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F3.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_F3 --output output/models/brooklyn_1m_250_F3.3mf

# G3: 96.125 x 187.5 mm, 1.97 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G3.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G3.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_G3 --output output/models/brooklyn_1m_250_G3.3mf

# B4: 233.875 x 214 mm, 4.89 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B4.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B4.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B4 --output output/models/brooklyn_1m_250_B4.3mf

# D4: 109 x 244.625 mm, 2.69 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D4.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D4.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_D4 --output output/models/brooklyn_1m_250_D4.3mf

# B4.2: 175 x 222.75 mm, 3.62 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B4.2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B4.2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B4.2 --output output/models/brooklyn_1m_250_B4.2.3mf

# E4: 171 x 171 mm, 2.71 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E4.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E4.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_E4 --output output/models/brooklyn_1m_250_E4.3mf

# F4: 239.125 x 174 mm, 3.20 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F4.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_F4.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_F4 --output output/models/brooklyn_1m_250_F4.3mf

# A4: 179 x 220 mm, 4.03 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A4.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A4.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_A4 --output output/models/brooklyn_1m_250_A4.3mf

# A5: 235.25 x 143 mm, 2.06 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_A5 --output output/models/brooklyn_1m_250_A5.3mf

# E5: 199 x 136 mm, 2.53 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_E5 --output output/models/brooklyn_1m_250_E5.3mf

# B5: 191 x 100 mm, 1.80 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B5 --output output/models/brooklyn_1m_250_B5.3mf

# C5: 149 x 106.875 mm, 1.25 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_C5 --output output/models/brooklyn_1m_250_C5.3mf

# D5: 135 x 163 mm, 2.12 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_D5 --output output/models/brooklyn_1m_250_D5.3mf

# G5: 145.125 x 201 mm, 2.95 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G5.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G5.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_G5 --output output/models/brooklyn_1m_250_G5.3mf

# A5.2: 159.5 x 227.875 mm, 2.74 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A5.2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_A5.2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_A5.2 --output output/models/brooklyn_1m_250_A5.2.3mf

# B6: 236.875 x 240 mm, 4.34 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B6.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B6.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B6 --output output/models/brooklyn_1m_250_B6.3mf

# C6: 225 x 246 mm, 5.06 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C6.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C6.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_C6 --output output/models/brooklyn_1m_250_C6.3mf

# D6: 89.125 x 125 mm, 0.88 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D6.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_D6.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_D6 --output output/models/brooklyn_1m_250_D6.3mf

# E6: 228 x 250 mm, 5.68 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E6.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E6.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_E6 --output output/models/brooklyn_1m_250_E6.3mf

# G6: 143.125 x 250 mm, 3.88 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G6.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_G6.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_G6 --output output/models/brooklyn_1m_250_G6.3mf

# C6.2: 223.5 x 247.25 mm, 3.37 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C6.2.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_C6.2.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_C6.2 --output output/models/brooklyn_1m_250_C6.2.3mf

# B7: 214.5 x 126 mm, 1.90 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B7.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_B7.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_B7 --output output/models/brooklyn_1m_250_B7.3mf

# E7: 189 x 79 mm, 1.55 km2
/Users/anton/Projects/3D-NYC/.venv/bin/python scripts/generate_3mf.py --bounding-polygon @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E7.geojson --print-frame @output/plans/brooklyn_1m_250/chunks/brooklyn_1m_250_E7.frame.json --scale 10794.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -3.0738 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id brooklyn_1m_250_E7 --output output/models/brooklyn_1m_250_E7.3mf
