#!/bin/sh
# Generated by scripts/plan_map_chunks.py. Run from the repository root.
# Plan the_villages_250: 2 plates at 1:10533.
# Every plate shares one print-frame rotation, terrain datum and relief
# factor; changing any of them for a single plate will break the seams.
set -eu

# A1: 241.5 x 249.125 mm, 4.34 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/the_villages_250/chunks/the_villages_250_A1.geojson --print-frame @output/plans/the_villages_250/chunks/the_villages_250_A1.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id the_villages_250_A1 --output output/models/the_villages_250_A1.3mf

# B1: 163.75 x 172.625 mm, 2.21 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/the_villages_250/chunks/the_villages_250_B1.geojson --print-frame @output/plans/the_villages_250/chunks/the_villages_250_B1.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id the_villages_250_B1 --output output/models/the_villages_250_B1.3mf
