#!/bin/sh
# Generated by scripts/plan_map_chunks.py. Run from the repository root.
# Plan manhattan_2m_240: 20 plates at 1:10533.
# Every plate shares one print-frame rotation, terrain datum and relief
# factor; changing any of them for a single plate will break the seams.
set -eu

# A1: 162.75 x 207.375 mm, 3.05 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A1.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A1.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A1 --output output/models/manhattan_2m_240_A1.3mf

# A2: 159.625 x 240 mm, 3.31 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A2.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A2.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A2 --output output/models/manhattan_2m_240_A2.3mf

# A3: 211.375 x 180 mm, 2.54 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A3.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A3.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A3 --output output/models/manhattan_2m_240_A3.3mf

# A4: 129.125 x 193 mm, 2.36 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A4.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A4.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A4 --output output/models/manhattan_2m_240_A4.3mf

# B4: 228.25 x 237 mm, 3.95 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B4.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B4.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B4 --output output/models/manhattan_2m_240_B4.3mf

# A5: 174 x 238 mm, 4.14 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A5.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A5.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A5 --output output/models/manhattan_2m_240_A5.3mf

# B5: 173.25 x 184 mm, 3.11 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B5.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B5.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B5 --output output/models/manhattan_2m_240_B5.3mf

# A6: 115.25 x 132 mm, 1.67 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A6.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A6.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A6 --output output/models/manhattan_2m_240_A6.3mf

# B6: 239.5 x 164 mm, 4.19 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B6.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B6.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B6 --output output/models/manhattan_2m_240_B6.3mf

# A7: 138.625 x 221 mm, 2.54 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A7.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A7.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A7 --output output/models/manhattan_2m_240_A7.3mf

# B7: 227.125 x 190 mm, 3.76 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B7.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B7.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B7 --output output/models/manhattan_2m_240_B7.3mf

# B8: 130.875 x 188 mm, 2.31 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B8.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B8.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B8 --output output/models/manhattan_2m_240_B8.3mf

# A8: 191.375 x 190 mm, 3.71 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A8.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A8.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A8 --output output/models/manhattan_2m_240_A8.3mf

# B9: 188 x 127 mm, 2.26 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B9.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B9.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B9 --output output/models/manhattan_2m_240_B9.3mf

# A9: 75 x 91 mm, 0.48 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A9.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A9.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A9 --output output/models/manhattan_2m_240_A9.3mf

# C9: 157.25 x 227 mm, 2.45 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_C9.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_C9.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_C9 --output output/models/manhattan_2m_240_C9.3mf

# A10: 172.5 x 235 mm, 2.29 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A10.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_A10.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_A10 --output output/models/manhattan_2m_240_A10.3mf

# B10: 112 x 213 mm, 2.04 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B10.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B10.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B10 --output output/models/manhattan_2m_240_B10.3mf

# C10: 163.75 x 172.625 mm, 2.21 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_C10.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_C10.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_C10 --output output/models/manhattan_2m_240_C10.3mf

# B11: 190.25 x 170 mm, 2.17 km2
python scripts/generate_3mf.py --bounding-polygon @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B11.geojson --print-frame @output/plans/manhattan_2m_240/chunks/manhattan_2m_240_B11.frame.json --scale 10533.000000 --grid-step-mm 0.125 --layer-height 0.16 --vertical-exaggeration 1 --terrain-origin-m -10.5482 --terrain-relief-factor 1.000000 --source-padding-m 20 --prime-tower off --job-id manhattan_2m_240_B11 --output output/models/manhattan_2m_240_B11.3mf
